/* Swiss Training Ledger: the main personal dashboard, built as an asymmetric daily operating sheet. */

import { type SetStateAction, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Activity, ArrowUpRight, BookOpen, Check, Download, Dumbbell, Github, Languages, LockKeyhole, Plus, RefreshCw, Save, Settings2, Sparkles, Timer, Trash2, TrendingUp, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CategoryBars, Heatmap, ProgressLine, SectionHeading, StatCard } from "@/components/TrackerWidgets";
import { exportWorkbook } from "@/lib/export";
import { GitHubConfig, syncToGitHub } from "@/lib/github";
import { blankEntry, DailyLog, formatDate, getLog, getStats, getStreaks, isoDate, japaneseMinutes, readStore, saveLog, totalMinutes, TrackerStore, workoutMinutes, writeStore } from "@/lib/tracker";

const today = isoDate(new Date());
const monthStart = `${today.slice(0, 7)}-01`;

function WorkoutChoice({ selected, title, detail, onClick }: { selected: boolean; title: string; detail: string; onClick: () => void }) {
  return <button className={`choice-card ${selected ? "selected" : ""}`} onClick={onClick}><span className="choice-check">{selected ? <Check size={14} /> : ""}</span><div><b>{title}</b><small>{detail}</small></div><ArrowUpRight size={16} /></button>;
}

function GatewayMark() {
  return <svg className="gateway-mark" viewBox="0 0 42 42" aria-label="Gateway Tracker"><path d="M8 7h7v28H8zM27 7h7v28h-7z" fill="currentColor" /><path d="m16 28 12-14v8l-12 13z" fill="#E84C3D" /></svg>;
}

export default function Home() {
  const [store, setStore] = useState<TrackerStore>(() => readStore());
  const [selectedDate, setSelectedDate] = useState(today);
  const [log, setLog] = useState<DailyLog>(() => getLog(readStore(), today));
  const [rangeFrom, setRangeFrom] = useState(monthStart);
  const [rangeTo, setRangeTo] = useState(today);
  const [github, setGithub] = useState<GitHubConfig>({ owner: "", repo: "", token: "", branch: "gateway-tracker-sync", baseBranch: "main", createPullRequest: true });
  const [syncing, setSyncing] = useState(false);
  const [localStatus, setLocalStatus] = useState<"ready" | "dirty" | "saved">("ready");
  const [isOnline, setIsOnline] = useState(() => typeof navigator === "undefined" ? true : navigator.onLine);
  useEffect(() => { setLog(getLog(store, selectedDate)); setLocalStatus("ready"); }, [selectedDate, store]);
  useEffect(() => { const setOnline = () => setIsOnline(true); const setOffline = () => setIsOnline(false); window.addEventListener("online", setOnline); window.addEventListener("offline", setOffline); return () => { window.removeEventListener("online", setOnline); window.removeEventListener("offline", setOffline); }; }, []);

  const setDraft = (update: SetStateAction<DailyLog>) => { setLog(update); setLocalStatus("dirty"); };
  const save = () => { const next = saveLog(store, log); setStore(next); writeStore(next); setLocalStatus("saved"); toast.success(`Saved ${formatDate(log.date, { day: "numeric", month: "short" })}`, { description: "Your local journal is saved on this device." }); };
  const stats = useMemo(() => getStats(store, rangeFrom, rangeTo), [store, rangeFrom, rangeTo]);
  const streaks = useMemo(() => getStreaks(store), [store]);
  const currentDayMinutes = totalMinutes(log);
  const updateWorkout = (key: keyof DailyLog["workout"], value: boolean | number | string) => setDraft((current) => ({ ...current, workout: { ...current.workout, [key]: value } }));
  const updateEntry = (id: string, key: string, value: string | number) => setDraft((current) => ({ ...current, japanese: current.japanese.map((entry) => entry.id === id ? { ...entry, [key]: value } : entry) }));
  const exportData = async () => { try { await exportWorkbook(store, rangeFrom, rangeTo); toast.success("XLSX ready", { description: "Your selected range was exported." }); } catch { toast.error("Export failed", { description: "Try a smaller date range and retry." }); } };
  const sync = async () => { if (!isOnline) { toast.error("You're offline", { description: "Your log stays safe on this device. Reconnect, then tap Sync again." }); return; } setSyncing(true); try { const result = await syncToGitHub(store, github); const next = { ...store, lastSyncedAt: result.timestamp }; setStore(next); writeStore(next); toast.success("GitHub snapshot created", { description: result.pullRequestUrl ? `PR ready: ${result.pullRequestUrl}` : `Branch ${result.branch} updated.` }); } catch (error) { toast.error("GitHub sync failed", { description: `${error instanceof Error ? error.message : "Check your repository settings."} Fix the issue and tap Sync again to retry.` }); } finally { setSyncing(false); } };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><GatewayMark /><div><b>GATEWAY</b><span>TRACKER / 01</span></div></div><div className="sidebar-rule" /><nav className="nav-list"><a className="nav-active" href="#today"><span>01</span><Activity size={16} />Today log</a><a href="#rhythm"><span>02</span><TrendingUp size={16} />Rhythm</a><a href="#export"><span>03</span><Download size={16} />Export</a></nav><div className="sidebar-bottom"><div className={`sync-state ${!isOnline ? "state-offline" : `state-${localStatus}`}`}><span className="status-dot" />{!isOnline ? "OFFLINE MODE" : localStatus === "dirty" ? "UNSAVED CHANGE" : "LOCAL JOURNAL"}<div>{!isOnline ? "Saved changes remain on this device" : localStatus === "dirty" ? "Save before closing this tab" : store.lastSyncedAt ? `Synced ${new Date(store.lastSyncedAt).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}` : localStatus === "saved" ? "Saved locally just now" : "No cloud backup yet"}</div></div><div className="sidebar-footer"><LockKeyhole size={14} /> Private by default</div></div></aside>
    <main className="main-shell"><header className="topbar"><div className="breadcrumb"><span>GATEWAY TRACKER</span><b>DAILY OPERATING SHEET</b></div><div className="top-actions"><span className="today-stamp">{today}</span><Dialog><DialogTrigger asChild><Button variant="outline" className="icon-button"><Github size={16} /> Sync</Button></DialogTrigger><DialogContent className="sync-dialog"><DialogHeader><DialogTitle>Sync to GitHub</DialogTitle><DialogDescription>Each sync appends an immutable JSON snapshot and updates the latest pointer. Your token remains in this browser only.</DialogDescription></DialogHeader><div className="dialog-grid"><div><Label htmlFor="owner">Owner</Label><Input id="owner" value={github.owner} onChange={(e) => setGithub({ ...github, owner: e.target.value })} placeholder="your-username" /></div><div><Label htmlFor="repo">Repository</Label><Input id="repo" value={github.repo} onChange={(e) => setGithub({ ...github, repo: e.target.value })} placeholder="gateway-tracker-data" /></div><div><Label htmlFor="token">Fine-grained token</Label><Input id="token" type="password" value={github.token} onChange={(e) => setGithub({ ...github, token: e.target.value })} placeholder="github_pat_…" /></div><div><Label htmlFor="branch">Sync branch</Label><Input id="branch" value={github.branch} onChange={(e) => setGithub({ ...github, branch: e.target.value })} /></div><div className="dialog-check"><input id="pr" type="checkbox" checked={github.createPullRequest} onChange={(e) => setGithub({ ...github, createPullRequest: e.target.checked })} /><Label htmlFor="pr">Create or reuse an open pull request</Label></div></div><Button onClick={sync} disabled={syncing}>{syncing ? <RefreshCw className="spin" size={16} /> : <Github size={16} />}{syncing ? "Syncing…" : "Create snapshot"}</Button><p className="dialog-footnote">Required repo permissions: Contents read/write; Pull requests read/write when PR mode is enabled. Never paste a token into a public code file.</p></DialogContent></Dialog><Dialog><DialogTrigger asChild><Button className="primary-button"><Settings2 size={16} /> Settings</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Tracker settings</DialogTitle><DialogDescription>Gateway Tracker is local-first. Your journal stays in this browser unless you explicitly export or sync it.</DialogDescription></DialogHeader><div className="settings-note"><Sparkles size={18} /><div><b>Target: JLPT N3</b><p>Recommended Japanese floor: 45 minutes. The tracker counts study and sentence-building minutes.</p></div></div></DialogContent></Dialog></div></header>
      <div className="content-wrap"><section className="hero-strip"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><span className="eyebrow light">PERSONAL OPERATING LEDGER / 2026</span><h1>Make the day count<br /><em>in minutes, not intentions.</em></h1><p>A single checkpoint for your training, Japanese study, and the space you keep for yourself.</p></div><div className="hero-marker">{today.slice(5).replace("-", ".")}<small>JAKARTA / LOCAL</small></div></section>{!isOnline && <div className="offline-banner" role="status"><WifiOff size={17} /><span><b>Offline mode.</b> Daily logs continue to save on this device. Reconnect before using GitHub Sync.</span></div>}
        <section id="today" className="section-block"><SectionHeading index="01" eyebrow={`Today / ${formatDate(selectedDate, { weekday: "short", day: "numeric", month: "short" })}`} title="Daily check-in" detail="Log the reps. Keep the thread." action={<div className="date-picker"><Label htmlFor="date">Entry date</Label><Input id="date" type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} /></div>} /><div className="today-grid"><div className="log-panel paper-panel"><div className="panel-label"><span>DAY LOG</span><span className="autosave"><span className="status-dot" />LOCAL SAVE</span></div>
          <div className="field-block"><div className="field-title"><Dumbbell size={17} /><div><b>Workout</b><span>Choose one or both. Scale with intent.</span></div><span className="field-index">A</span></div><div className="workout-choices"><WorkoutChoice selected={log.workout.ladder} title="1,500-REP LADDER" detail="1 → 10 → 1 / bodyweight" onClick={() => updateWorkout("ladder", !log.workout.ladder)} /><WorkoutChoice selected={log.workout.cindy} title="CINDY WOD" detail="20 min AMRAP / 5–10–15" onClick={() => updateWorkout("cindy", !log.workout.cindy)} /></div>{(log.workout.ladder || log.workout.cindy) && <div className="workout-inputs">{log.workout.ladder && <div className="mini-input"><Label>Ladder rounds</Label><Input type="number" min="0" value={log.workout.ladderRounds} onChange={(e) => updateWorkout("ladderRounds", Number(e.target.value))} /></div>}{log.workout.cindy && <div className="mini-input"><Label>Cindy rounds</Label><Input type="number" min="0" value={log.workout.cindyRounds} onChange={(e) => updateWorkout("cindyRounds", Number(e.target.value))} /></div>}{log.workout.ladder && <div className="mini-input"><Label>Ladder time</Label><Input type="number" min="0" value={log.workout.ladderMinutes} onChange={(e) => updateWorkout("ladderMinutes", Number(e.target.value))} /></div>}{log.workout.cindy && <div className="mini-input"><Label>Cindy time</Label><Input type="number" min="0" value={log.workout.cindyMinutes} onChange={(e) => updateWorkout("cindyMinutes", Number(e.target.value))} /></div>}</div>}</div>
          <div className="field-block japanese-block"><div className="field-title"><Languages size={17} /><div><b>Japanese / JLPT N3 path</b><span>Kotoba, kanji, bunpou — then make it live in a sentence.</span></div><span className="field-index">B</span></div><div className="entry-stack">{log.japanese.map((entry, index) => <div className="entry-card" key={entry.id}><div className="entry-top"><span className="entry-number">{String(index + 1).padStart(2, "0")}</span><select aria-label={`Japanese entry ${index + 1} category`} value={entry.type} onChange={(e) => updateEntry(entry.id, "type", e.target.value)}><option value="kotoba">Kotoba</option><option value="kanji">Kanji</option><option value="bunpou">Bunpou</option></select><select aria-label={`Japanese entry ${index + 1} JLPT level`} value={entry.jlpt} onChange={(e) => updateEntry(entry.id, "jlpt", e.target.value)}><option value="N3">N3</option><option value="N4">N4</option><option value="N5">N5</option></select>{log.japanese.length > 1 && <button className="ghost-icon" onClick={() => setDraft((current) => ({ ...current, japanese: current.japanese.filter((item) => item.id !== entry.id) }))} aria-label="Remove Japanese entry"><Trash2 size={15} /></button>}</div><div className="entry-inputs"><Input aria-label={`Japanese entry ${index + 1} content`} value={entry.content} onChange={(e) => updateEntry(entry.id, "content", e.target.value)} placeholder={entry.type === "kanji" ? "漢字" : entry.type === "bunpou" ? "〜わけではない" : "覚える"} /><Input aria-label={`Japanese entry ${index + 1} furigana or reading`} value={entry.reading} onChange={(e) => updateEntry(entry.id, "reading", e.target.value)} placeholder="Furigana / reading" /><div className="minute-input"><Input aria-label={`Japanese entry ${index + 1} study minutes`} type="number" min="0" value={entry.studyMinutes} onChange={(e) => updateEntry(entry.id, "studyMinutes", Number(e.target.value))} /><span>study min</span></div></div><div className="sentence-row"><Input aria-label={`Japanese entry ${index + 1} example sentence`} value={entry.sentence} onChange={(e) => updateEntry(entry.id, "sentence", e.target.value)} placeholder="Example sentence using this item…" /><div className="minute-input"><Input aria-label={`Japanese entry ${index + 1} sentence-building minutes`} type="number" min="0" value={entry.sentenceMinutes} onChange={(e) => updateEntry(entry.id, "sentenceMinutes", Number(e.target.value))} /><span>build min</span></div></div></div>)}</div><Button variant="outline" className="add-entry" onClick={() => setDraft((current) => ({ ...current, japanese: [...current.japanese, blankEntry()] }))}><Plus size={15} /> Add another item</Button></div>
          <div className="field-block free-block"><div className="field-title"><Timer size={17} /><div><b>Free minutes</b><span>Protect a little unstructured space.</span></div><span className="field-index">C</span></div><div className="free-row"><div className="free-number"><Input type="number" min="0" value={log.freeMinutes} onChange={(e) => setDraft((current) => ({ ...current, freeMinutes: Number(e.target.value) }))} /><span>minutes</span></div><Input value={log.note} onChange={(e) => setDraft((current) => ({ ...current, note: e.target.value }))} placeholder="One line for the day…" /></div></div><Button className="save-day" onClick={save}><Save size={16} /> Save daily checkpoint <span>{currentDayMinutes} min logged</span></Button></div>
          <div className="today-aside"><div className="signal-card"><div className="panel-label"><span>TODAY SIGNAL</span><span className="signal-mark">●</span></div><div className="signal-number">{currentDayMinutes}<small>min</small></div><p>{currentDayMinutes ? "The thread is alive. Keep the next action small." : "No minutes logged yet. Start with one honest block."}</p><div className="signal-breakdown"><div><span>WORKOUT</span><b>{workoutMinutes(log)} min</b></div><div><span>JAPANESE</span><b>{japaneseMinutes(log)} min</b></div></div></div><div className="target-card"><div className="target-title"><BookOpen size={16} /><b>Recommended floor</b></div><strong>45 min</strong><p>Japanese minimum toward N3. Split it between study and sentence-making.</p><div className="target-bar"><span style={{ width: `${Math.min(100, (japaneseMinutes(log) / 45) * 100)}%` }} /></div><small>{Math.min(45, japaneseMinutes(log))} / 45 min</small></div><div className="image-note"><div className="practice-grid" aria-hidden="true" /><div><span className="eyebrow">THE PRACTICE</span><b>Train the body.<br />Build the sentence.</b></div></div></div></div></section>
        <section id="rhythm" className="section-block rhythm-section"><SectionHeading index="02" eyebrow="Rhythm / contribution view" title="See the thread." detail="A GitHub-style contribution field for the hours that became real." action={<div className="range-inline"><Input type="date" value={rangeFrom} onChange={(e) => setRangeFrom(e.target.value)} /><span>→</span><Input type="date" value={rangeTo} onChange={(e) => setRangeTo(e.target.value)} /></div>} /><div className="stats-grid"><StatCard label="Current streak" value={`${streaks.current} days`} note={`Longest run ${streaks.longest} days`} accent="red" icon={TrendingUp} /><StatCard label="Range minutes" value={`${stats.totalMinutes}`} note={`${stats.activeDays} active days`} accent="ink" icon={Timer} /><StatCard label="Japanese items" value={`${stats.items}`} note="with sentence field" accent="moss" icon={Languages} /><StatCard label="Workout days" value={`${stats.logs.filter((item) => item.workout.ladder || item.workout.cindy).length}`} note="Ladder / Cindy" accent="blue" icon={Dumbbell} /></div><div className="rhythm-grid"><div className="paper-panel contribution-panel"><div className="panel-label"><span>CONTRIBUTION FIELD</span><span>INTENSITY = MINUTES</span></div><Heatmap store={store} /></div><div className="paper-panel trend-panel"><div className="panel-label"><span>14-DAY TREND</span><span>ALL CATEGORIES</span></div><ProgressLine store={store} /></div></div><div className="breakdown-panel paper-panel"><div><div className="panel-label"><span>CATEGORY BREAKDOWN</span><span>SELECTED RANGE</span></div><h3>Where the minutes went.</h3><p>Compare the physical and language practice without losing the shape of the day.</p></div><CategoryBars stats={stats} /></div></section>
        <section id="export" className="section-block export-section"><SectionHeading index="03" eyebrow="Export / durable record" title="Take the ledger with you." detail="A beautiful, customizable workbook for every month or any date range." action={<Button className="primary-button" onClick={exportData}><Download size={16} /> Export XLSX</Button>} /><div className="export-grid"><div className="export-card"><div className="export-icon"><Download size={22} /></div><div><b>Four sheets, one record.</b><p>Summary, Daily Log, Japanese Detail, and Workout Log are prepared with frozen headers and readable column widths.</p></div><span className="file-tag">.XLSX</span></div><div className="export-card"><div className="export-icon"><Github size={22} /></div><div><b>Versioned backup, on demand.</b><p>GitHub sync is explicit, serialized, and append-only so your history remains reviewable.</p></div><span className="file-tag">.JSON</span></div></div><footer><span>GATEWAY TRACKER / PRIVATE PERSONAL TOOL</span><span>Source of truth: this browser + your chosen backup</span><span>v1.0 / local-first</span></footer></section>
      </div><nav className="mobile-bottom-nav" aria-label="Quick actions"><a href="#today"><Activity size={18} /><span>Today</span></a><a href="#rhythm"><TrendingUp size={18} /><span>Rhythm</span></a><a href="#export"><Download size={18} /><span>Export</span></a><button onClick={save}><Save size={18} /><span>Save</span></button></nav></main>
  </div>;
}
