import { type SetStateAction, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Activity, AlarmClock, ArrowUpRight, Bell, BellOff, BookOpen, Check, Download, Dumbbell, Github, Languages, LockKeyhole, Pause, Play, Plus, RefreshCw, Save, Settings2, Sparkles, Timer, Trash2, TrendingUp, Upload, WifiOff, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CategoryBars, Heatmap, ProgressLine, SectionHeading, StatCard, WeeklyTargetBars } from "@/components/TrackerWidgets";
import { createJapaneseBatch, parseJapaneseBatch, suggestBatchMinutes } from "@/lib/batch";
import { exportWorkbook } from "@/lib/export";
import { GitHubConfig, syncToGitHub } from "@/lib/github";
import { alarmEndTime, fireReminder, formatAlarmCountdown, notificationStatus, NotificationStatus, remainingAlarmSeconds, requestReminderPermission, shouldFireDailyReminder } from "@/lib/reminder";
import { blankEntry, DailyLog, formatDate, getDailyPlan, getLog, getSettings, getStats, getStreaks, getWeeklyProgress, isoDate, japaneseBatches, japaneseItemCount, japaneseMinutes, readStore, saveLog, saveSettings, totalMinutes, TrackerStore, typeLabel, workoutMinutes, writeStore } from "@/lib/tracker";

const today = isoDate(new Date());
const monthStart = `${today.slice(0, 7)}-01`;
const ALARM_STORAGE_KEY = "gateway-focus-alarm-ends-at";
const DAILY_REMINDER_STORAGE_KEY = "gateway-daily-reminder-last-fired";

function WorkoutChoice({ selected, title, detail, onClick }: { selected: boolean; title: string; detail: string; onClick: () => void }) {
  return <button className={`choice-card ${selected ? "selected" : ""}`} onClick={onClick}><span className="choice-check">{selected ? <Check size={14} /> : ""}</span><div><b>{title}</b><small>{detail}</small></div><ArrowUpRight size={16} /></button>;
}

function GatewayMark() {
  return <svg className="gateway-mark" viewBox="0 0 42 42" aria-label="Gateway Tracker"><path d="M8 7h7v28H8zM27 7h7v28h-7z" fill="currentColor" /><path d="m16 28 12-14v8l-12 13z" fill="#E84C3D" /></svg>;
}

export default function Home() {
  const [store, setStore] = useState<TrackerStore>(() => readStore());
  const [selectedDate, setSelectedDate] = useState(today);
  const [log, setLog] = useState<DailyLog>(() => getLog(readStore(), today));
  const [rangeFrom, setRangeFrom] = useState(monthStart);
  const [rangeTo, setRangeTo] = useState(today);
  const [github, setGithub] = useState<GitHubConfig>({ owner: "", repo: "", token: "", branch: "gateway-tracker-sync", baseBranch: "main", createPullRequest: false });
  const [syncing, setSyncing] = useState(false);
  const [localStatus, setLocalStatus] = useState<"ready" | "dirty" | "saved">("ready");
  const [isOnline, setIsOnline] = useState(() => typeof navigator === "undefined" ? true : navigator.onLine);
  const [batchRaw, setBatchRaw] = useState("");
  const [batchType, setBatchType] = useState<"kotoba" | "kanji" | "bunpou">("kotoba");
  const [batchJLPT, setBatchJLPT] = useState<"N5" | "N4" | "N3">("N3");
  const [batchStudyMinutes, setBatchStudyMinutes] = useState(0);
  const [manualOpen, setManualOpen] = useState(false);
  const [notification, setNotification] = useState<NotificationStatus>(() => notificationStatus());
  const [alarmEndsAt, setAlarmEndsAt] = useState(() => {
    if (typeof window === "undefined") return 0;
    const value = Number(window.localStorage.getItem(ALARM_STORAGE_KEY));
    return Number.isFinite(value) && value > Date.now() ? value : 0;
  });
  const [remainingSeconds, setRemainingSeconds] = useState(() => alarmEndsAt ? remainingAlarmSeconds(alarmEndsAt) : 0);
  const audioContext = useRef<AudioContext | null>(null);

  useEffect(() => { setLog(getLog(store, selectedDate)); setLocalStatus("ready"); }, [selectedDate, store]);
  useEffect(() => { const online = () => setIsOnline(true); const offline = () => setIsOnline(false); window.addEventListener("online", online); window.addEventListener("offline", offline); return () => { window.removeEventListener("online", online); window.removeEventListener("offline", offline); }; }, []);
  useEffect(() => {
    if (!alarmEndsAt) return;
    const tick = () => {
      const remaining = remainingAlarmSeconds(alarmEndsAt);
      setRemainingSeconds(remaining);
      if (remaining !== 0) return;
      window.localStorage.removeItem(ALARM_STORAGE_KEY);
      setAlarmEndsAt(0);
      if (audioContext.current) {
        const oscillator = audioContext.current.createOscillator();
        const gain = audioContext.current.createGain();
        oscillator.connect(gain); gain.connect(audioContext.current.destination);
        oscillator.frequency.value = 880; gain.gain.setValueAtTime(0.06, audioContext.current.currentTime);
        oscillator.start(); oscillator.stop(audioContext.current.currentTime + 0.55);
      }
      const method = fireReminder("Focus block selesai", "Catat hasilnya atau mulai blok berikutnya.");
      toast.success("Focus block selesai", { description: method === "notification" ? "Notifikasi juga sudah dikirim." : "Catat hasilnya sebelum lanjut." });
    };
    tick(); const interval = window.setInterval(tick, 1000); return () => window.clearInterval(interval);
  }, [alarmEndsAt]);

  const setDraft = (update: SetStateAction<DailyLog>) => { setLog(update); setLocalStatus("dirty"); };
  const save = () => { const next = saveLog(store, log); setStore(next); writeStore(next); setLocalStatus("saved"); toast.success(`Tersimpan · ${formatDate(log.date, { day: "numeric", month: "short" })}`, { description: `${japaneseItemCount(log)} item Jepang dan ${totalMinutes(log)} menit tercatat.` }); };
  const updateSettings = (patch: Parameters<typeof saveSettings>[1]) => { const next = saveSettings(store, patch); setStore(next); writeStore(next); };
  const stats = useMemo(() => getStats(store, rangeFrom, rangeTo), [store, rangeFrom, rangeTo]);
  const streaks = useMemo(() => getStreaks(store), [store]);
  const plan = useMemo(() => getDailyPlan(store, today), [store]);
  const settings = useMemo(() => getSettings(store), [store]);
  const weekly = useMemo(() => getWeeklyProgress(store, today), [store]);
  useEffect(() => {
    const evaluate = () => {
      if (plan.remainingMinutes === 0) return;
      const reminder = shouldFireDailyReminder(settings.dailyReminderTime, window.localStorage.getItem(DAILY_REMINDER_STORAGE_KEY));
      if (!reminder.due) return;
      window.localStorage.setItem(DAILY_REMINDER_STORAGE_KEY, reminder.date);
      const method = fireReminder("Gateway check-in", `Masih ada ${plan.remainingMinutes} menit Jepang. Mulai ${plan.recommendedBlockMinutes} menit dulu.`);
      toast.message("Waktunya check-in", { description: method === "notification" ? "Notifikasi juga sudah dikirim." : `Sisa ${plan.remainingMinutes} menit. Mulai blok kecil sekarang.` });
    };
    evaluate();
    const interval = window.setInterval(evaluate, 60_000);
    return () => window.clearInterval(interval);
  }, [plan.remainingMinutes, plan.recommendedBlockMinutes, settings.dailyReminderTime]);
  const parsedBatch = useMemo(() => parseJapaneseBatch(batchRaw), [batchRaw]);
  const currentDayMinutes = totalMinutes(log);
  const updateWorkout = (key: keyof DailyLog["workout"], value: boolean | number | string) => setDraft((current) => ({ ...current, workout: { ...current.workout, [key]: value } }));
  const updateEntry = (id: string, key: string, value: string | number) => setDraft((current) => ({ ...current, japanese: current.japanese.map((entry) => entry.id === id ? { ...entry, [key]: value } : entry) }));
  const exportData = async () => { try { await exportWorkbook(store, rangeFrom, rangeTo); toast.success("XLSX siap", { description: "Daily log, batch Jepang, dan summary sudah diekspor." }); } catch { toast.error("Ekspor gagal", { description: "Coba rentang tanggal yang lebih kecil." }); } };
  const sync = async () => { if (!isOnline) { toast.error("Lo sedang offline", { description: "Data tetap aman di perangkat ini. Sync lagi saat online." }); return; } setSyncing(true); try { const result = await syncToGitHub(store, github); const next = { ...store, lastSyncedAt: result.timestamp }; setStore(next); writeStore(next); toast.success("Snapshot GitHub dibuat", { description: `Branch ${result.branch} sudah diupdate.` }); } catch (error) { toast.error("GitHub sync gagal", { description: `${error instanceof Error ? error.message : "Periksa repo."} Lalu tap Sync lagi.` }); } finally { setSyncing(false); } };
  const addBatch = () => {
    const created = createJapaneseBatch({ raw: batchRaw, type: batchType, jlpt: batchJLPT, studyMinutes: batchStudyMinutes || suggestBatchMinutes(parsedBatch.length) });
    if (!created) { toast.error("Tidak ada item yang terbaca", { description: "Tempel satu item per baris, atau pisahkan dengan koma/titik koma." }); return; }
    setDraft((current) => ({ ...current, batches: [...(current.batches ?? []), created] }));
    setBatchRaw(""); setBatchStudyMinutes(0); toast.success(`${created.items.length} ${typeLabel[created.type].toLowerCase()} masuk batch`, { description: `${created.studyMinutes} menit tercatat sebagai sesi.` });
  };
  const startFocus = () => {
    const minutes = plan.recommendedBlockMinutes || settings.focusBlockMinutes;
    const endsAt = alarmEndTime(minutes);
    if (typeof AudioContext !== "undefined" && !audioContext.current) audioContext.current = new AudioContext();
    audioContext.current?.resume();
    window.localStorage.setItem(ALARM_STORAGE_KEY, String(endsAt)); setAlarmEndsAt(endsAt); setRemainingSeconds(remainingAlarmSeconds(endsAt));
    toast.success(`Fokus ${minutes} menit dimulai`, { description: notification === "granted" ? "Notifikasi akan muncul saat selesai bila sistem mengizinkan." : "Alarm visual aktif. Aktifkan notifikasi agar lebih tegas." });
  };
  const cancelFocus = () => { window.localStorage.removeItem(ALARM_STORAGE_KEY); setAlarmEndsAt(0); setRemainingSeconds(0); };
  const enableNotifications = async () => { const next = await requestReminderPermission(); setNotification(next); if (next === "granted") toast.success("Notifikasi aktif"); else toast.message("Alarm visual tetap aktif", { description: "Notifikasi sistem belum diizinkan di perangkat ini." }); };
  const weeklyTargetAction = <Dialog><DialogTrigger asChild><Button variant="outline" className="weekly-target-edit"><Settings2 size={15} /> Target</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Kontrak target mingguan</DialogTitle><DialogDescription>Semua target memakai menit, dihitung Senin sampai Minggu, dan bisa nol jika kategori sedang tidak diprioritaskan.</DialogDescription></DialogHeader><div className="weekly-settings-grid">{(["kotoba", "kanji", "bunpou", "workout"] as const).map((category) => <div key={category}><Label htmlFor={`weekly-${category}`}>{category === "bunpou" ? "Bunpou" : category[0].toUpperCase() + category.slice(1)}</Label><Input id={`weekly-${category}`} type="number" min="0" max="2400" value={settings.weeklyTargets[category]} onChange={(e) => updateSettings({ weeklyTargets: { ...settings.weeklyTargets, [category]: Number(e.target.value) } })} /></div>)}</div></DialogContent></Dialog>;

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><GatewayMark /><div><b>GATEWAY</b><span>TRACKER / 02</span></div></div><div className="sidebar-rule" /><nav className="nav-list" aria-label="Navigasi utama"><a className="nav-active" href="#today"><span>01</span><Activity size={16} />Pilot hari ini</a><a href="#rhythm"><span>02</span><TrendingUp size={16} />Rhythm</a><a href="#export"><span>03</span><Download size={16} />Export</a></nav><div className="sidebar-bottom"><div className={`sync-state ${!isOnline ? "state-offline" : `state-${localStatus}`}`}><span className="status-dot" />{!isOnline ? "OFFLINE MODE" : localStatus === "dirty" ? "BELUM DISIMPAN" : "LOCAL JOURNAL"}<div>{!isOnline ? "Perubahan aman di perangkat ini" : localStatus === "dirty" ? "Simpan sebelum menutup tab" : store.lastSyncedAt ? `Synced ${new Date(store.lastSyncedAt).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}` : "Belum ada backup cloud"}</div></div><div className="sidebar-footer"><LockKeyhole size={14} /> Personal by default</div></div></aside>
    <main className="main-shell"><header className="topbar"><div className="breadcrumb"><span>GATEWAY TRACKER</span><b>DAILY PILOT</b></div><div className="top-actions"><span className="today-stamp">{today}</span><Dialog><DialogTrigger asChild><Button variant="outline" className="icon-button"><Github size={16} /> Sync</Button></DialogTrigger><DialogContent className="sync-dialog"><DialogHeader><DialogTitle>Backup ke GitHub</DialogTitle><DialogDescription>Sync ini membuat snapshot immutable dan mengupdate pointer terbaru langsung ke branch yang lo pilih.</DialogDescription></DialogHeader><div className="dialog-grid"><div><Label htmlFor="owner">Owner</Label><Input id="owner" value={github.owner} onChange={(e) => setGithub({ ...github, owner: e.target.value })} placeholder="your-username" /></div><div><Label htmlFor="repo">Repository</Label><Input id="repo" value={github.repo} onChange={(e) => setGithub({ ...github, repo: e.target.value })} placeholder="gateway-tracker-data" /></div><div><Label htmlFor="token">Fine-grained token</Label><Input id="token" type="password" value={github.token} onChange={(e) => setGithub({ ...github, token: e.target.value })} placeholder="github_pat_…" /></div><div><Label htmlFor="branch">Sync branch</Label><Input id="branch" value={github.branch} onChange={(e) => setGithub({ ...github, branch: e.target.value })} /></div></div><Button onClick={sync} disabled={syncing}>{syncing ? <RefreshCw className="spin" size={16} /> : <Github size={16} />}{syncing ? "Syncing…" : "Buat snapshot"}</Button><p className="dialog-footnote">Token hanya berada di memori browser dan tidak disimpan sebagai data tracker.</p></DialogContent></Dialog><Dialog><DialogTrigger asChild><Button className="primary-button"><Settings2 size={16} /> Settings</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Parameter pilot</DialogTitle><DialogDescription>Algoritme memakai angka ini untuk menentukan blok berikutnya dan recovery target.</DialogDescription></DialogHeader><div className="dialog-grid"><div><Label htmlFor="daily-target">Target Jepang harian</Label><Input id="daily-target" type="number" min="15" max="180" value={settings.dailyJapaneseTarget} onChange={(e) => updateSettings({ dailyJapaneseTarget: Number(e.target.value) })} /></div><div><Label htmlFor="focus-block">Durasi blok fokus</Label><Input id="focus-block" type="number" min="5" max="90" value={settings.focusBlockMinutes} onChange={(e) => updateSettings({ focusBlockMinutes: Number(e.target.value) })} /></div></div><div className="settings-note"><Sparkles size={18} /><div><b>Algoritme diadaptasi, bukan menghukum.</b><p>Target naik terbatas setelah bolong, turun sedikit setelah ritme stabil, dan prioritas memilih kategori yang kurang terisi dalam 14 hari.</p></div></div></DialogContent></Dialog></div></header>
      <div className="content-wrap">
        <section className="pilot-panel" id="today"><div className="pilot-copy"><span className="eyebrow light">NEXT ACTION / {typeLabel[plan.priority].toUpperCase()}</span><h1>{plan.remainingMinutes ? "Jangan buka dashboard." : "Hari ini sudah beres."}<em>{plan.remainingMinutes ? " Mulai blok berikutnya." : " Jangan paksa tambah."}</em></h1><p>{plan.instruction}</p><div className="pilot-metrics"><div><span>DONE</span><b>{plan.completedMinutes}<small>m</small></b></div><div><span>TARGET</span><b>{plan.targetMinutes}<small>m</small></b></div><div><span>7D AVG</span><b>{plan.sevenDayAverage}<small>m</small></b></div><div><span>GAP</span><b>{plan.missedDays}<small>d</small></b></div></div></div><div className="focus-dock"><div className="focus-label"><AlarmClock size={17} /><span>{alarmEndsAt ? "FOCUS RUNNING" : "LOCAL FOCUS ALARM"}</span></div><strong>{alarmEndsAt ? formatAlarmCountdown(remainingSeconds) : `${plan.recommendedBlockMinutes || settings.focusBlockMinutes}:00`}</strong><p>{alarmEndsAt ? "Tetap di sini. Alarm visual dan notifikasi akan mengakhiri blok." : "Alarm berjalan saat app aktif. Install PWA agar akses lebih cepat."}</p>{alarmEndsAt ? <Button className="focus-button pause" onClick={cancelFocus}><Pause size={16} /> Stop block</Button> : <Button className="focus-button" onClick={startFocus}><Play size={16} /> Mulai {plan.recommendedBlockMinutes || settings.focusBlockMinutes} menit</Button>}<button className="notification-toggle" onClick={enableNotifications}>{notification === "granted" ? <Bell size={14} /> : <BellOff size={14} />}{notification === "granted" ? "Notifikasi aktif" : "Aktifkan notifikasi"}</button></div></section>
        {!isOnline && <div className="offline-banner" role="status"><WifiOff size={17} /><span><b>Offline mode.</b> Log tetap tersimpan di perangkat ini. Sambungkan internet hanya saat ingin sync atau install ulang.</span></div>}
        <aside className="reminder-strip"><div className="reminder-copy"><AlarmClock size={17} /><div><span>DAILY NUDGE / WIB</span><b>{settings.dailyReminderTime} setiap hari, selama Gateway terbuka atau terpasang.</b></div></div><Dialog><DialogTrigger asChild><Button variant="outline" className="reminder-edit">Atur jam</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Jadwal daily nudge</DialogTitle><DialogDescription>Gateway mengecek jadwal setiap menit saat aplikasi aktif. Ini bukan alarm background saat browser ditutup.</DialogDescription></DialogHeader><div className="reminder-time-field"><Label htmlFor="reminder-time">Waktu (WIB)</Label><Input id="reminder-time" type="time" value={settings.dailyReminderTime} onChange={(e) => updateSettings({ dailyReminderTime: e.target.value })} /></div></DialogContent></Dialog></aside>

        <section className="section-block action-section"><SectionHeading index="01" eyebrow={`Hari ini / ${formatDate(selectedDate, { weekday: "short", day: "numeric", month: "short" })}`} title="Log yang nggak bikin lo kerja dua kali." detail="Input besar sebagai batch. Detail manual cuma saat memang butuh contoh kalimat atau catatan spesifik." action={<div className="date-picker"><Label htmlFor="date">Tanggal</Label><Input id="date" type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} /></div>} /><div className="today-grid"><div className="log-panel paper-panel"><div className="panel-label"><span>DAILY INPUT</span><span className="autosave"><span className="status-dot" />{localStatus === "dirty" ? "DIRTY" : "LOCAL"}</span></div>
          <div className="field-block"><div className="field-title"><Dumbbell size={17} /><div><b>Workout</b><span>Pilih hanya yang benar-benar lo lakukan. Durasi dipakai untuk total dan recovery plan.</span></div><span className="field-index">A</span></div><div className="workout-choices"><WorkoutChoice selected={log.workout.ladder} title="1,500-REP LADDER" detail="1 → 10 → 1 / bodyweight" onClick={() => updateWorkout("ladder", !log.workout.ladder)} /><WorkoutChoice selected={log.workout.cindy} title="CINDY WOD" detail="20 min AMRAP / 5–10–15" onClick={() => updateWorkout("cindy", !log.workout.cindy)} /></div>{(log.workout.ladder || log.workout.cindy) && <div className="workout-inputs">{log.workout.ladder && <div className="mini-input"><Label>Ladder rounds</Label><Input type="number" min="0" value={log.workout.ladderRounds} onChange={(e) => updateWorkout("ladderRounds", Number(e.target.value))} /></div>}{log.workout.cindy && <div className="mini-input"><Label>Cindy rounds</Label><Input type="number" min="0" value={log.workout.cindyRounds} onChange={(e) => updateWorkout("cindyRounds", Number(e.target.value))} /></div>}{log.workout.ladder && <div className="mini-input"><Label>Ladder time</Label><Input type="number" min="0" value={log.workout.ladderMinutes} onChange={(e) => updateWorkout("ladderMinutes", Number(e.target.value))} /></div>}{log.workout.cindy && <div className="mini-input"><Label>Cindy time</Label><Input type="number" min="0" value={log.workout.cindyMinutes} onChange={(e) => updateWorkout("cindyMinutes", Number(e.target.value))} /></div>}</div>}</div>
          <div className="field-block japanese-batch-block"><div className="field-title"><Upload size={17} /><div><b>Japanese batch capture</b><span>Tempel 500 kotoba sekaligus. Satu baris = satu item; duplikat dibuang otomatis.</span></div><span className="field-index">B</span></div><div className="batch-controls"><select aria-label="Batch category" value={batchType} onChange={(e) => setBatchType(e.target.value as typeof batchType)}><option value="kotoba">Kotoba</option><option value="kanji">Kanji</option><option value="bunpou">Bunpou</option></select><select aria-label="Batch JLPT level" value={batchJLPT} onChange={(e) => setBatchJLPT(e.target.value as typeof batchJLPT)}><option value="N3">N3</option><option value="N4">N4</option><option value="N5">N5</option></select><div className="minute-input"><Input aria-label="Batch study minutes" type="number" min="0" value={batchStudyMinutes || suggestBatchMinutes(parsedBatch.length)} onChange={(e) => setBatchStudyMinutes(Number(e.target.value))} /><span>study min</span></div></div><textarea className="batch-textarea" value={batchRaw} onChange={(e) => setBatchRaw(e.target.value)} placeholder={"覚える\n確保\n見直す\n… tempel sampai 1.000 item di sini"} /><div className="batch-footer"><span>{parsedBatch.length ? `${parsedBatch.length} item valid · saran ${suggestBatchMinutes(parsedBatch.length)} menit` : "Paste list dulu; item kosong dan duplikat tidak akan dihitung."}</span><Button onClick={addBatch} disabled={!parsedBatch.length}><Plus size={15} /> Tambah batch</Button></div><div className="batch-list">{japaneseBatches(log).map((batch) => <div className="batch-chip" key={batch.id}><div><b>{batch.items.length} {typeLabel[batch.type]}</b><span>{batch.jlpt} · {batch.studyMinutes + batch.sentenceMinutes}m · {batch.items.slice(0, 3).join(" · ")}{batch.items.length > 3 ? "…" : ""}</span></div><button onClick={() => setDraft((current) => ({ ...current, batches: japaneseBatches(current).filter((item) => item.id !== batch.id) }))} aria-label="Remove batch"><X size={15} /></button></div>)}</div></div>
          <div className="field-block detail-block"><button className="detail-trigger" onClick={() => setManualOpen((open) => !open)}><div><Languages size={17} /><span><b>Detail manual opsional</b><small>Pakai kalau perlu contoh kalimat atau satu grammar spesifik.</small></span></div>{manualOpen ? "Tutup" : "Buka"}</button>{manualOpen && <div className="entry-stack">{log.japanese.map((entry, index) => <div className="entry-card" key={entry.id}><div className="entry-top"><span className="entry-number">{String(index + 1).padStart(2, "0")}</span><select aria-label={`Japanese entry ${index + 1} category`} value={entry.type} onChange={(e) => updateEntry(entry.id, "type", e.target.value)}><option value="kotoba">Kotoba</option><option value="kanji">Kanji</option><option value="bunpou">Bunpou</option></select><select aria-label={`Japanese entry ${index + 1} JLPT level`} value={entry.jlpt} onChange={(e) => updateEntry(entry.id, "jlpt", e.target.value)}><option value="N3">N3</option><option value="N4">N4</option><option value="N5">N5</option></select>{log.japanese.length > 1 && <button className="ghost-icon" onClick={() => setDraft((current) => ({ ...current, japanese: current.japanese.filter((item) => item.id !== entry.id) }))} aria-label="Remove Japanese entry"><Trash2 size={15} /></button>}</div><div className="entry-inputs"><Input aria-label={`Japanese entry ${index + 1} content`} value={entry.content} onChange={(e) => updateEntry(entry.id, "content", e.target.value)} placeholder="Item spesifik" /><Input aria-label={`Japanese entry ${index + 1} reading`} value={entry.reading} onChange={(e) => updateEntry(entry.id, "reading", e.target.value)} placeholder="Reading" /><div className="minute-input"><Input aria-label={`Japanese entry ${index + 1} study minutes`} type="number" min="0" value={entry.studyMinutes} onChange={(e) => updateEntry(entry.id, "studyMinutes", Number(e.target.value))} /><span>study min</span></div></div><div className="sentence-row"><Input aria-label={`Japanese entry ${index + 1} example sentence`} value={entry.sentence} onChange={(e) => updateEntry(entry.id, "sentence", e.target.value)} placeholder="Contoh kalimat…" /><div className="minute-input"><Input aria-label={`Japanese entry ${index + 1} sentence minutes`} type="number" min="0" value={entry.sentenceMinutes} onChange={(e) => updateEntry(entry.id, "sentenceMinutes", Number(e.target.value))} /><span>build min</span></div></div></div>)}</div>}<Button variant="outline" className="add-entry" onClick={() => { setManualOpen(true); setDraft((current) => ({ ...current, japanese: [...current.japanese, blankEntry()] })); }}><Plus size={15} /> Tambah detail</Button></div>
          <div className="field-block free-block"><div className="field-title"><Timer size={17} /><div><b>Free minutes</b><span>Bukan KPI. Hanya supaya hari lo tetap kebaca secara utuh.</span></div><span className="field-index">C</span></div><div className="free-row"><div className="free-number"><Input type="number" min="0" value={log.freeMinutes} onChange={(e) => setDraft((current) => ({ ...current, freeMinutes: Number(e.target.value) }))} /><span>minutes</span></div><Input value={log.note} onChange={(e) => setDraft((current) => ({ ...current, note: e.target.value }))} placeholder="Satu catatan yang berguna untuk besok…" /></div></div><Button className="save-day" onClick={save}><Save size={16} /> Simpan checkpoint <span>{currentDayMinutes} min · {japaneseItemCount(log)} item</span></Button></div>
          <aside className="today-aside"><div className="signal-card"><div className="panel-label"><span>DECISION SIGNAL</span><span className="signal-mark">●</span></div><div className="signal-number">{plan.remainingMinutes}<small>min left</small></div><p>{plan.remainingMinutes ? `Prioritas hari ini: ${typeLabel[plan.priority]}. Jangan tambah form baru sebelum blok ini jalan.` : "Target selesai. Stop mengejar angka dan pilih recovery yang benar."}</p><div className="signal-breakdown"><div><span>JAPANESE</span><b>{japaneseMinutes(log)} min</b></div><div><span>ITEMS</span><b>{japaneseItemCount(log)}</b></div></div></div><div className="target-card adaptive-card"><div className="target-title"><BookOpen size={16} /><b>Kenapa target ini?</b></div><strong>{plan.targetMinutes} min</strong><p>{plan.missedDays ? `Re-entry ${Math.min(20, plan.missedDays * 4)}m lebih ringan karena ${plan.missedDays} hari putus.` : "Ritme stabil; target mengikuti baseline lo."} Rata-rata 7 hari: {plan.sevenDayAverage}m.</p><div className="target-bar"><span style={{ width: `${Math.min(100, (plan.completedMinutes / plan.targetMinutes) * 100)}%` }} /></div><small>{plan.completedMinutes} / {plan.targetMinutes} min</small></div></aside></div></section>
        <section id="rhythm" className="section-block rhythm-section"><SectionHeading index="02" eyebrow="Rhythm / weekly contract" title="Tutup target dulu, baru lihat pola." detail="Progress ini menghitung Senin–Minggu. Setelah itu, grafik menjelaskan apakah ritme dan alokasinya sehat." action={<div className="range-inline"><Input type="date" value={rangeFrom} onChange={(e) => setRangeFrom(e.target.value)} /><span>→</span><Input type="date" value={rangeTo} onChange={(e) => setRangeTo(e.target.value)} /></div>} /><WeeklyTargetBars weekly={weekly.progress} from={weekly.from} to={weekly.to} action={weeklyTargetAction} /><div className="stats-grid"><StatCard label="Streak aktif" value={`${streaks.current} hari`} note={`Terpanjang ${streaks.longest} hari`} accent="red" icon={TrendingUp} /><StatCard label="Menit range" value={`${stats.totalMinutes}`} note={`${stats.activeDays} hari aktif`} accent="ink" icon={Timer} /><StatCard label="Item Jepang" value={`${stats.items}`} note="termasuk batch" accent="moss" icon={Languages} /><StatCard label="Workout" value={`${stats.logs.filter((item) => item.workout.ladder || item.workout.cindy).length}`} note="hari tercatat" accent="blue" icon={Dumbbell} /></div><div className="rhythm-grid"><div className="paper-panel contribution-panel"><div className="panel-label"><span>CONSISTENCY FIELD</span><span>INTENSITY = MINUTES</span></div><Heatmap store={store} /></div><div className="paper-panel trend-panel"><div className="panel-label"><span>14-DAY LOAD</span><span>CEK OVER/UNDERLOAD</span></div><ProgressLine store={store} /></div></div><div className="breakdown-panel paper-panel"><div><div className="panel-label"><span>ALLOCATION CHECK</span><span>SELECTED RANGE</span></div><h3>Apa yang kurang dapat waktu?</h3><p>Algoritme daily pilot memakai ketimpangan ini untuk memilih prioritas berikutnya.</p></div><CategoryBars stats={stats} /></div></section>
        <section id="export" className="section-block export-section"><SectionHeading index="03" eyebrow="Export / portable record" title="Bawa log, bukan sekadar tampilan." detail="Workbook memisahkan daily log, detail manual, dan batch supaya 500 kotoba tetap bisa dibaca." action={<Button className="primary-button" onClick={exportData}><Download size={16} /> Export XLSX</Button>} /><div className="export-grid"><div className="export-card"><div className="export-icon"><Download size={22} /></div><div><b>Five sheets, zero cleanup.</b><p>Summary, Daily Log, Japanese Detail, Japanese Batches, dan Workout Log. Batch tidak dipaksa jadi 500 form rows.</p></div><span className="file-tag">.XLSX</span></div><div className="export-card"><div className="export-icon"><Github size={22} /></div><div><b>Snapshot, bukan drama sync.</b><p>Backup bersifat append-only dan langsung ke branch backup. Source app tetap dipush ke main.</p></div><span className="file-tag">.JSON</span></div></div><footer><span>GATEWAY TRACKER / PRIVATE PERSONAL TOOL</span><span>Source of truth: this browser + chosen backup</span><span>v2.0 / daily pilot</span></footer></section>
      </div><nav className="mobile-bottom-nav" aria-label="Aksi cepat"><a href="#today"><Activity size={18} /><span>Pilot</span></a><a href="#rhythm"><TrendingUp size={18} /><span>Rhythm</span></a><a href="#export"><Download size={18} /><span>Export</span></a><button onClick={save}><Save size={18} /><span>Save</span></button></nav></main>
  </div>;
}
